title: Down South Entertainment | Margaret River
email: lee@downsouthentertainment.com.au
description: > # this means to ignore newlines until "baseurl:"
  A music and entertainment agency in Margaret River, Western Australia.
baseurl: downsouthentertainment.github.io
url: 'http://downsouthentertainment.com.au'

# Where things are
source:      .
destination:  ./_site
layouts_dir:  ./_layouts
data_dir: ./_data
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    0.0.0.0

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink: pretty
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []


# Prose settings
prose:
  siteurl: "http://downsouthentertainment.com.au"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          label: "Layout: artists, feature, testimonials"
          placeholder: "Choose Layout"
          value: ""
          type: "text"
      - name: "category"
        field:
          element: "text"
          label: "Category: solo, dj, feature, band, special, testimonial"
          placeholder: "Choose Category"
          value: ""
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Image, e.g. /images/your_image.jpg"
          placeholder: "Select your image"
          value: "/images/"
          type: "text"
      - name: "desc"
        field:
          element: "text"
          label: "description - Google SEO 160 characters"
          placeholder: "Add Description"
          value: ""
          type: "text"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
